'use client';
import { useMemo, useState } from 'react';
import clsx from 'clsx';
import { allHands, getDecisionActions, getRangeActionDefs } from '@/lib/poker';
import { analyzeRoadmapRange } from '@/lib/roadmap-flash';
import { hexRgba } from '@/lib/utils';
import type { RoadmapPhase, SelectedTab } from '@/lib/types';
import { Button } from '@/components/ui/Button';

type Zone = 'all' | 'frontier' | 'outside' | 'mixed' | `action:${string}`;

export function RangeLearningWorkspace({ selectedTab, phase, onBack, onAdvance, onStartNext }: { selectedTab: SelectedTab; phase: RoadmapPhase; onBack: () => void; onAdvance: () => void; onStartNext: () => void }) {
  const analysis = useMemo(() => analyzeRoadmapRange(selectedTab.rangeMap), [selectedTab.rangeMap]);
  const actions = useMemo(() => getRangeActionDefs(selectedTab.rangeMap), [selectedTab.rangeMap]);
  const [zone, setZone] = useState<Zone>('all');
  const [selectedHand, setSelectedHand] = useState<string | null>(null);
  const activeHands = useMemo(() => {
    if (zone === 'all') return new Set(allHands().map(item => item.hand));
    if (zone === 'frontier') return new Set(analysis.innerBottoms);
    if (zone === 'outside') return new Set(analysis.boundaryFolds);
    if (zone === 'mixed') return new Set(analysis.mixed);
    const action = zone.slice('action:'.length);
    return new Set(allHands().filter(({ hand }) => getDecisionActions(hand, selectedTab.rangeMap).some(item => item.action === action)).map(item => item.hand));
  }, [zone, analysis, selectedTab.rangeMap]);

  if (phase === 'practice') return <StepLaunchScreen selectedTab={selectedTab} onBack={onBack} eyebrow="Exploration terminée" title={`Valide maintenant ${selectedTab.name}`} description="Le Flash ciblera les frontières, les mixes et chacune des actions présentes dans cette range." action="Lancer le Flash Roadmap" onStart={onStartNext}/>;
  if (phase === 'validate') return <StepLaunchScreen selectedTab={selectedTab} onBack={onBack} eyebrow="Flash validé" title="Étape suivante : reconstituer la range" description="Passe maintenant en Grille pour reconstruire entièrement la range de mémoire." action="Lancer la Grille" onStart={onStartNext} success/>;
  if (phase === 'retention') return <StepLaunchScreen selectedTab={selectedTab} onBack={onBack} eyebrow="Range acquise" title={`${selectedTab.name} est en répétition espacée`} description="La Roadmap te proposera une révision SRS lorsque la mémoire commencera à décroître." action="Retour à la Roadmap" onStart={onBack} success/>;

  return <div className="flex-1 min-h-0 flex flex-col bg-bg overflow-hidden">
    <header className="flex-shrink-0 border-b border-border bg-bg2 px-4 sm:px-6 py-3">
      <div className="max-w-7xl mx-auto flex items-center gap-3"><button onClick={onBack} className="text-xs text-muted hover:text-text">← Roadmap</button><div className="w-px h-6 bg-border"/><div className="min-w-0"><div className="text-[9px] uppercase tracking-wider font-bold text-accent">{phase === 'discover' ? 'Découvrir' : 'Comprendre'}</div><h2 className="text-sm sm:text-base font-bold truncate">{selectedTab.catName} · {selectedTab.name}</h2></div><div className="ml-auto hidden sm:flex items-center gap-2 text-[10px] text-muted"><span>{analysis.played.length} mains jouées</span><span>·</span><span>{analysis.mixed.length} mixes 50/50</span></div></div>
    </header>
    <div className="flex-1 min-h-0 overflow-y-auto p-3 sm:p-5 lg:p-7">
      <div className="max-w-7xl mx-auto grid lg:grid-cols-[240px_minmax(0,1fr)_260px] gap-4 min-h-full">
        <aside className="rounded-xl border border-border bg-bg2 p-3 h-fit lg:sticky lg:top-0"><div className="section-label">Zones de la range</div><div className="space-y-1.5 mt-3"><ZoneButton active={zone === 'all'} label="Vue complète" count={169} onClick={() => setZone('all')}/><ZoneButton active={zone === 'frontier'} label="Frontière jouée" count={analysis.innerBottoms.length} onClick={() => setZone('frontier')}/><ZoneButton active={zone === 'outside'} label="Folds voisins" count={analysis.boundaryFolds.length} onClick={() => setZone('outside')}/><ZoneButton active={zone === 'mixed'} label="Mixes 50/50" count={analysis.mixed.length} onClick={() => setZone('mixed')}/></div><div className="section-label mt-5">Actions du fichier</div><div className="space-y-1.5 mt-3">{actions.map(([action, color]) => <ZoneButton key={action} active={zone === `action:${action}`} label={action} count={allHands().filter(({ hand }) => getDecisionActions(hand, selectedTab.rangeMap).some(item => item.action === action)).length} color={color} onClick={() => setZone(`action:${action}`)}/>)}</div></aside>

        <main className="rounded-xl border border-border bg-bg2 p-3 sm:p-5 h-fit"><div className="flex items-start justify-between gap-3 mb-4"><div><div className="section-label">{zoneLabel(zone)}</div><p className="text-[11px] text-muted mt-1">Les mains hors de la zone restent visibles pour conserver la forme de la range.</p></div><strong className="text-sm">{activeHands.size}</strong></div><div className="grid grid-cols-13 gap-[2px] max-w-[760px] mx-auto">{allHands().map(({ hand }) => <RangeCell key={hand} hand={hand} rangeMap={selectedTab.rangeMap} actionDefs={actions} active={activeHands.has(hand)} selected={selectedHand === hand} onClick={() => setSelectedHand(hand)}/>)}</div><div className="flex flex-wrap gap-3 mt-4">{actions.map(([action, color]) => <span key={action} className="inline-flex items-center gap-1.5 text-[10px] text-muted"><span className="w-2 h-2 rounded-full" style={{ background: color }}/>{action}</span>)}</div></main>

        <aside className="rounded-xl border border-border bg-bg2 p-4 h-fit lg:sticky lg:top-0">{selectedHand ? <HandInspector hand={selectedHand} selectedTab={selectedTab} frontier={analysis.innerBottoms.includes(selectedHand)} outside={analysis.boundaryFolds.includes(selectedHand)}/> : <div className="py-8 text-center"><div className="text-sm font-bold">Explore librement</div><p className="text-[11px] text-muted mt-2">Choisis une zone, puis clique sur une main pour voir ses actions.</p></div>}<div className="border-t border-border mt-4 pt-4"><p className="text-[11px] text-muted leading-relaxed">{phase === 'discover' ? 'Commence par la vue complète et parcours chaque couleur.' : 'Concentre-toi sur la frontière, les folds voisins, les mixes et chaque action distincte.'}</p><Button variant="primary" className="w-full mt-3" onClick={onAdvance}>{phase === 'discover' ? 'J’ai cartographié la range' : 'J’ai terminé l’exploration'} →</Button></div></aside>
      </div>
    </div>
  </div>;
}

function StepLaunchScreen({ onBack, eyebrow, title, description, action, onStart, success }: { selectedTab: SelectedTab; onBack: () => void; eyebrow: string; title: string; description: string; action: string; onStart: () => void; success?: boolean }) { return <div className="flex-1 overflow-y-auto p-4 sm:p-8 bg-gradient-to-b from-bg3/30 to-bg"><div className="max-w-2xl mx-auto"><button onClick={onBack} className="text-xs text-muted hover:text-text">← Retour à la Roadmap</button><div className={clsx('rounded-2xl border p-7 sm:p-10 text-center mt-8', success ? 'border-green/35 bg-green/10' : 'border-accent/35 bg-accent/10')}><div className={clsx('text-sm font-bold', success ? 'text-green' : 'text-accent')}>{eyebrow}</div><h2 className="text-2xl font-black mt-2">{title}</h2><p className="text-sm text-muted mt-3">{description}</p><Button variant="primary" className="mt-6" onClick={onStart}>{action} →</Button></div></div></div>; }

function RangeCell({ hand, rangeMap, actionDefs, active, selected, onClick }: { hand: string; rangeMap: SelectedTab['rangeMap']; actionDefs: [string, string][]; active: boolean; selected: boolean; onClick: () => void }) { const decisions = getDecisionActions(hand, rangeMap); const colors = new Map(actionDefs); let background: string; if (decisions.length === 1) background = hexRgba(colors.get(decisions[0].action) ?? '#6b7280', decisions[0].action === 'Fold' ? .2 : .86); else background = `linear-gradient(135deg,${hexRgba(colors.get(decisions[0].action) ?? '#888',.88)} 50%,${hexRgba(colors.get(decisions[1].action) ?? '#6b7280',.88)} 50%)`; return <button onClick={onClick} title={hand} className={clsx('aspect-square min-w-0 rounded-[3px] flex items-center justify-center text-[clamp(6px,1vw,10px)] font-bold text-white transition-all', !active && 'opacity-[.12] saturate-0', active && 'hover:scale-110 hover:z-10', selected && 'ring-2 ring-yellow z-10 scale-110')} style={{ background }}>{hand}</button>; }
function ZoneButton({ active, label, count, onClick, color }: { active: boolean; label: string; count: number; onClick: () => void; color?: string }) { return <button onClick={onClick} className={clsx('w-full min-h-9 rounded-lg border px-2.5 flex items-center gap-2 text-left text-[11px]', active ? 'border-accent bg-accent/12 text-text' : 'border-border text-muted hover:text-text hover:border-border2')}><span className="w-2 h-2 rounded-full flex-shrink-0" style={{ background: color ?? (active ? '#6c63ff' : '#6b7280') }}/><span className="truncate flex-1">{label}</span><strong>{count}</strong></button>; }
function HandInspector({ hand, selectedTab, frontier, outside }: { hand: string; selectedTab: SelectedTab; frontier: boolean; outside: boolean }) { const decisions = getDecisionActions(hand, selectedTab.rangeMap); return <div><div className="text-3xl font-black">{hand}</div><div className="flex flex-wrap gap-1.5 mt-3">{frontier && <span className="text-[9px] rounded-full bg-yellow/10 text-yellow border border-yellow/30 px-2 py-1">Frontière jouée</span>}{outside && <span className="text-[9px] rounded-full bg-bg4 text-muted border border-border px-2 py-1">Fold voisin</span>}{decisions.length > 1 && <span className="text-[9px] rounded-full bg-accent/10 text-accent border border-accent/30 px-2 py-1">Mix 50/50</span>}</div><div className="space-y-2 mt-4">{decisions.map(action => <div key={action.action} className="rounded-lg border border-border bg-bg3 p-3"><div className="flex items-center gap-2"><span className="w-2.5 h-2.5 rounded-full" style={{ background: action.color }}/><strong className="text-xs">{action.action}</strong><span className="ml-auto text-xs font-bold">{Math.round(action.freq * 100)}%</span></div></div>)}</div></div>; }
function zoneLabel(zone: Zone): string { if (zone === 'all') return 'Vue complète'; if (zone === 'frontier') return 'Frontière jouée'; if (zone === 'outside') return 'Folds voisins'; if (zone === 'mixed') return 'Mixes 50/50'; return zone.slice('action:'.length); }
